substitutions:
  _PROJECT_NAME: take-home-test

timeout: 1200s

steps:
  - name: gcr.io/cloud-builders/docker
    id: "Multistage Docker Build"
    secretEnv: [JFROG_PASSWORD]
    entrypoint: "bash"
    args:
      - "-c"
      - |
        docker login --username=take-home-test-cloudbuild --password=$$JFROG_PASSWORD

        docker build . --target php \
          -t chaugh/${_PROJECT_NAME}-php:${TAG_NAME}

        docker push chaugh/${_PROJECT_NAME}-php:${TAG_NAME}

  ## Trigger jenkins job when all pushes to JFrog complete
  - name: "gcr.io/cloud-builders/curl"
    args:
      [
        "-H",
        "Content-type: application/json",
        "-d",
        '{"jenkins_job_token": "start-${_PROJECT_NAME}-jenkinsfile", "git_tag_id": "$TAG_NAME"}',
        "-X",
        "POST",
        "https://us-central1-stage-development-167809.cloudfunctions.net/CfToIAP",
      ]
    id: "Trigger jenkins"

## Google KMS KEY for JFROG_PASSWORD Login
secrets:
  - kmsKeyName: projects/stage-development-167809/locations/global/keyRings/JFROGKEYRING/cryptoKeys/JFROGCRYPTOKEY
    secretEnv:
      JFROG_PASSWORD: afdadsfadsfasdfasdfadsfasdfadsf
